### ISSUE TITLE
格式化函数讨论

### ISSUE THREAD

**Issue by NewGod** [NewGod/PDSL#18]
在 #17 里面实现了PhyVar，但是格式化函数并没有实现，我觉得我们得讨论下PDSL对user支持什么样的格式化输出
这就交给你决定了 @bluecat1024

**Comment by bluecat1024** [comment]
X.as(Pa)，X.as(N*m**-2)之类的，或提前或之后做字典转化；
难点是不是在于relation的数据结构，怎么在联系图上完成单位的查找和数量转换
能想到的是都向下找到基础单位。

**Comment by NewGod** [comment]
> X.as(Pa)，X.as(N*m**-2)之类的，或提前或之后做字典转化；
> 难点是不是在于relation的数据结构，怎么在联系图上完成单位的查找和数量转换
> 能想到的是都向下找到基础单位。

我感觉这里的问题是
如果`x = 1 Pa`,那么 x.as(N)你应该怎么处理
所以说尽量的把这个X.as()这个函数给他的输入输出给规定清楚先？

**Comment by NewGod** [comment]
目前得出来的结论是，我们只支持如果x = 1 m/s^2那么 x.as(N) = 1N，其他情况都会报错
