### ISSUE TITLE
C or python? This is a question.

### ISSUE THREAD

**Issue by NewGod** [NewGod/PDSL#9]
下面对语法应该使用的格式来进行讨论
1. 缩进
c ({}) or python (tab)?
2. for
c (for (;;)) or python(for in) 
此部分交给 @bluecat1024 来决定 
请顺便吧做法在这里提一下

**Comment by bluecat1024** [comment]
缩进就使用大括号吧
for 可以使用in， 用括号，数字表达区间和跨度
